# Site
repository: sproogen/resume-theme
favicon: images/yvesicon.ico

# Content configuration version
version: 2

# Personal info
name: Yves R. Sagaert
title: Assistant Professor | VIVES University of Applied Sciences | KU Leuven | IESÉG Management School
email: yves.sagaert@vives.be
website: yForecasting.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  yForecasting
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: yvessagaert
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: yvesrsagaert.wordpress.com
  icon: fas fa-globe
  url: https://yvesrsagaert.wordpress.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Yves_Sagaert_Profielfoto_AI.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Yves R. Sagaert and I'm an Assistant Professor at VIVES University of Applied Sciences (Kortrijk, Belgium) and IESÉG Management School (Lille, France). My research focus is on research in Predictive AI (Artificial Intelligence), Demand Forecasting, Inventory Management, Variable Selection and Leading Indicators. 
  
  You can follow my [Blog](https://yvesrsagaert.wordpress.com/) for stories, updates and case studies. 


content:
  - title: Research interests # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Demand Forecasting with Leading Indicators
        # link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          It's better to look ahead and prepare, than to look back and regret. 
          
          Map out your future path - but do it in pencil.
          
        description: | # this will include new lines to allow paragraphs
          My main research focus is on <mark>demand forecasting</mark> for <mark>supply chain management</mark>. Here, traditional models typically extraploate historical demand data to forecast future expected demand. However, external events can have a big impact. The business setting is getting more volatile and the impact of external events is increasing. I research how to extend the traditional approach with <mark>Leading Indicators</mark>. While there is a lot of external data available, the question arises how to select and include this information in a statistical forecasting model which isn't a black box. This model should be comprehensive and transparent, so that business users can understand the contribution of each piece of information. 
          
  - title: In the press
    layout: text
    content: | # this will include new lines to allow paragraphs
      **KennisWest: Impact with Applied AI research**
      
        I gave an interview on how applied research can help SMEs and what the impact can be on the production floor. The article is available in [NL](pdf/Interview_YvesRSagaert_WestVlaanderenWerkt_2024_NL.pdf) or [EN](pdf/Interview_YvesRSagaert_WestVlaanderenWerkt_2024_EN.pdf).
        
      **International Institue of Forecasters**
      
        The IIF is an organisation with forecasting researchers from all around the world who are operating in business or academia. The IIF releases the academic journal International Journal of Forecasting (IJF), as well as a more business-oriented journal Foresight: The International Journal of Applied Forecasting. 
        I gave an interview as a forecasting member of the IJF, which can be found [online](https://forecasters.org/blog/2019/04/19/member-profile-yves-sagaert/) or in [pdf](pdf/Interview_IIF_YvesRSagaert_2019.pdf).
        

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: VIVES University of Applied Sciences | KU Leuven
        link: https://www.vives.be/nl
        link_text: vives.be
        sub_title: Assistant Professor
        caption: 2020 - Present
        quote: >
          Bringing innovation closer
        description: | # this will include new lines to allow paragraphs
            I focus on applied research on predictive analytics with machine learning \& AI (e.g. sales forecasting, student learning forecasting). I am leading my research group at VIVES and together we aim to bring innovative predictive AI closer to practice. 
            Next to this comes project management of internal and external projects, obtaining grants, lecturing, supervising bachelor/master theses and mentoring PhD students. 
            
      - layout: left
        title: IÉSEG School of Management
        link: https://www.ieseg.fr/en/
        link_text: ieseg.fr
        sub_title: Adjunct Professor
        caption: 2024 - Present
        quote: >
          Teaching the next generation of professionals
        description: | # this will include new lines to allow paragraphs
            I collaborate on research with a focus on inventory management and supply chain management. Next to my research collaboration, I teach algorithmic thinking and artificial intelligence algorithms using Python. 
      
      - layout: left
        title: Arcelor Mittal
        link: https://belgium.arcelormittal.com/
        link_text: belgium.arcelormittal.com
        sub_title: Strategic Innovation Manager for Harbour & Railway
        caption: 2017 - 2020
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            I optimised logistic routing and inventory management and I had a focus on innovation via big data & analytics. I was leading several internal innovation projects and creating a strategic vision to deploy self-driving trains in the next decade.
            
      - layout: left
        title: Solventure
        link: http://www.solventure.eu/
        link_text: solventure.eu
        sub_title: S&OP and Forecasting Research Consultant
        caption: 2013 - 2017
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            I provide executive training, design and teach forecasting courses to professionals in retail and Business-to-Business. Back in these days, I started up the Big Data pillar within the company. My main focus was on research interactions with global supply chain managers and the start-up of new R&D team to valorise my PhD research.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ghent University
        caption: 2013 - 2017
        sub_title: Doctor of Philosophy in Industrial Engineering and Operations Research
        quote: >
          Improving accuracy and robustness of global tactical sales forecasts in a B2B environment
        description: | # this will include new lines to allow paragraphs
          I developed a framework to improve sales forecasts by including the most relevant external information, such as weather, promotions and market leading indicators in addition to the historical structure

      - layout: left
        title: Ghent University
        caption: 2011 - 2013
        sub_title: Master of Science in Industrial Engineering and Operations Research
        quote: >
          Enhancing sales forecasts through the use of adequate exogenous indicators: A case study
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: Howest University of Applied Sciences
        caption: 2007 - 2011
        sub_title: Master of Science in Electrotechnics and Automation
        quote: >
          Optimisation of Profibus network at Cargill Izegem
        description: | # this will include new lines to allow paragraphs
        

  - title: When I am not forecasting
    layout: text
    content: | # this will include new lines to allow paragraphs
      I love gardening, cooking and woodworking. 
        

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
